// Generated by CoffeeScript 1.6.2
var alternativeJST, ui, ui_options;

alternativeJST = "<button class='alternative' value=<%=value%>>                    <%= value %>                  </button>";

ui_options = {
  playBtn: $('#play'),
  alternativesDiv: $('#alternatives'),
  alternatives: ['A', 'B', 'C'],
  alternativeTpl: _.template(alternativeJST)
};

ui = new Ui(ui_options);

ui.render();

ui.play();

/*
//@ sourceMappingURL=gtc.map
*/
