// Generated by CoffeeScript 1.6.2
var Ui;

Ui = (function() {
  function Ui(options) {
    this.alternatives = options.alternatives;
    this.alternativeTpl = options.alternativeTpl;
    this.alternativesDiv = options.alternativesDiv;
    options.playBtn.bind('click', this.play);
  }

  Ui.prototype.submitAnswer = function() {
    return console.log('sending...');
  };

  Ui.prototype.play = function() {
    return console.log('playing...');
  };

  Ui.prototype.generateAlternativesHtml = function() {
    var alternative, alternativesHtmlArray;

    alternativesHtmlArray = (function() {
      var _i, _len, _ref, _results;

      _ref = this.alternatives;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        alternative = _ref[_i];
        _results.push(this.alternativeTpl({
          value: alternative
        }));
      }
      return _results;
    }).call(this);
    return alternativesHtmlArray.join(' ');
  };

  Ui.prototype.render = function() {
    var alternativesHtml;

    alternativesHtml = this.generateAlternativesHtml();
    this.alternativesDiv.html(alternativesHtml);
    return this.alternativesDiv.find('.alternative').bind('click', this.submitAnswer);
  };

  return Ui;

})();

/*
//@ sourceMappingURL=ui.map
*/
